image:
  file: ./.gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
- port: 3000
  onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
- name: change nim version
  command: choosenim 1.2.0
- name: start up docker-compose
  command: docker-compose up -d --remove-orphans

vscode:
  extensions:
  - nimsaem.nimvscode
  - asciidoctor.asciidoctor-vscode
