version: '3'

services:
  nim-dev:
    build:
      context: .
      dockerfile: ./vscode.dockerfile
    image: nim-dev:1.2.0

  selenium-hub:
    image: selenium/hub:3.141.59-20210830
    container_name: selenium-hub
    ports:
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=10

  firefox:
    &node
    image: selenium/node-firefox:3.141.59-20210830
    container_name: selenium-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - test-site
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5

  chrome:
    <<: *node
    image: selenium/node-chrome:3.141.59-20210830
    container_name: selenium-chrome

  test-site:
    container_name: test-site
    image: nginx:1.21.3
    volumes:
      - ./tests/test-pages:/usr/share/nginx/html
    ports:
      - 8080:80
