name: gen docs for main

on:
  push:
    branches:
    - main
    - feature/*

jobs:
  gen_docs_deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: make output docs dir
      shell: bash
      id: make_dir
      run: |
        mkdir -p htmldocs/develop
        echo "::set-output name=output_dir::htmldocs/develop"

    - name: start docker-compose
      shell: bash
      run: |
        docker-compose up -d --remove-orphans
    
    - name: generate docs
      shell: bash
      env:
        OUTPUT_DIR: ${{ steps.make_dir.outputs.output_dir }}
      run: |
        docker exec nim-app nimble doc --index:on --project --out:${OUTPUT_DIR} src/selenimum.nim

    - name: create index.html
      shell: bash
      env:
        OUTPUT_DIR: ${{ steps.make_dir.outputs.output_dir }}
      run: |
        cat << 'EOF' > ${OUTPUT_DIR}/index.html
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta http-equiv="refresh" content="0; url=./selenimum.html">
        </head>
        <body>
          redirect to <a href="./selenimum.html">selenimum.html</a>  
        </body>
        </html>
        EOF

    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./htmldocs
        keep_files: true
