name: gen docs

on:
  push:
    branches:
    - feature/gen-docs-on-actions

jobs:
  gen_docs_deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: generate docs with docker-compose
      run: |
        docker-compose up -d --remove-orphans
        docker exec nim-app nimble docs
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./htmldocs
        keep_files: true
